# K-nearest neighbors

KNN là một trong những thuật toán học có giám sát đơn giản nhất trong Machine Learning. 

Khi training, thuật toán này không học bất cứ một điều gì từ tập dự liệu, vậy nên thuật toán này được xếp vào loại **Lazy Learning**.

KNN có thể giải quyết 2 bài toán học có giám sát:
- Classification 
- Regressing 

Với KNN, trong bài toán Classification, label của một điểm dữ liệu mới được suy ra trực tiếp từ K điểm dữ liệu gần nhất trong tập dữ liệu. 

Trong bài toán Regression, đầu ra của một điểm dữ liệu là trung bình có trọng số của đầu ra những điểm gần nhất



(Note) Nên dùng nhiều hàng xóm thay vì 1, những cũng nên dùng quá nhiều

? Tại sao lại không nên dùng 1 hàng xóm - Vì có thể xảy ra trường hợp lấy lỗi, nhiều, dẫn đến đưa ra kết quả sai

? Tại sao không nên lấy quá nhiều hàng xóm - Vì điều này có thể dẫn đến phá vở cấu trúc bề mặt chứa dữ liệu (có thể dễ nhậ ra trong bài toán hồi quy, khi kết quả được tính bằng việc lấy trung bình trọng số)


### Code

In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn import neighbors, datasets

In [2]:
iris = datasets.load_iris()

iris_X = iris.data
iris_y = iris.target 

X0 = iris_X[iris_y == 0 ] 
X1 = iris_X[iris_y == 1 ] 
X2 = iris_X[iris_y == 2 ] 

print('\nSamples from class 0:\n', X0[:5])

print('\nSamples from class 1:\n', X1[:5])

print('\nSamples from class 2:\n', X2[:5])


Samples from class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Samples from class 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

Samples from class 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


In [3]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(
    iris_X, iris_y, test_size=0.3, random_state=42
)

print ("Training size: %d" %len(y_train))
print ("Test size    : %d" %len(y_test))

Training size: 105
Test size    : 45


In [4]:
model = neighbors.KNeighborsClassifier(n_neighbors=10,p=2) 
model.fit(X_train,y_train) 
y_pred = model.predict(X_test) 

for true_label, pred_label in zip(y_test, y_pred):
    print(f"Thực tế: {true_label}, Dự đoán: {pred_label}")

Thực tế: 1, Dự đoán: 1
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 1, Dự đoán: 1
Thực tế: 0, Dự đoán: 0
Thực tế: 1, Dự đoán: 1
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 1, Dự đoán: 1
Thực tế: 2, Dự đoán: 2
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 1, Dự đoán: 1
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 1, Dự đoán: 1
Thực tế: 2, Dự đoán: 2
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 2, Dự đoán: 2
Thực tế: 2, Dự đoán: 2
Thực tế: 2, Dự đoán: 2
Thực tế: 2, Dự đoán: 2
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 1, Dự đoán: 1
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 1, Dự đoán: 1
Thực tế: 0,

**Phương pháp đánh giá** 

Để đánh giá độ chính xác của thuật toán KNN Classifier, xem có bao nhiêu điểm trong test data được dự đoán đúng, chia cho tổng số lượng trong tập test ra độ chính xác

In [5]:
from sklearn.metrics import accuracy_score 

print ("Accuracy of 10NN (customized weights): %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Accuracy of 10NN (customized weights): 100.00 %


**Đánh trọng số cho các điểm lân cận**

Trong kỹ thuật major voting bên trên, mỗi trong 10 điểm gần nhất được coi là có vai trò như nhau và giá trị lá phiếu của mỗi điểm này là như nhau. Như thế là không công bằng, vì rõ ràng rằng những điểm gần hơn nên có trọng số cao hơn (càng thân cận thì càng tin tưởng). 

Vậy nên sẽ đánh trọng số khác nhau cho mỗi trong 10 điểm gần nhất này. Cách đánh trọng số phải thoải mãn điều kiện là một điểm càng gần điểm test data thì phải được đánh trọng số càng cao (tin tưởng hơn). 

Cách đơn giản nhất là lấy nghịch đảo của khoảng cách này. (Trong trường hợp test data trùng với 1 điểm dữ liệu trong training data, tức khoảng cách bằng 0, ta lấy luôn label của điểm training data).

Scikit-learn giúp đơn giản hóa việc này bằng cách gán giá trị weights = 'distance'. (Giá trị mặc định của weights là 'uniform', tương ứng với việc coi tất cả các điểm lân cận có giá trị như nhau như ở trên).




In [6]:
model = neighbors.KNeighborsClassifier(n_neighbors=10,p=2, weights='distance') 
model.fit(X_train,y_train) 
y_pred = model.predict(X_test) 

for true_label, pred_label in zip(y_test, y_pred):
    print(f"Thực tế: {true_label}, Dự đoán: {pred_label}")

Thực tế: 1, Dự đoán: 1
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 1, Dự đoán: 1
Thực tế: 0, Dự đoán: 0
Thực tế: 1, Dự đoán: 1
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 1, Dự đoán: 1
Thực tế: 2, Dự đoán: 2
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 1, Dự đoán: 1
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 1, Dự đoán: 1
Thực tế: 2, Dự đoán: 2
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 2, Dự đoán: 2
Thực tế: 2, Dự đoán: 2
Thực tế: 2, Dự đoán: 2
Thực tế: 2, Dự đoán: 2
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 1, Dự đoán: 1
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 0, Dự đoán: 0
Thực tế: 2, Dự đoán: 2
Thực tế: 1, Dự đoán: 1
Thực tế: 1, Dự đoán: 1
Thực tế: 0,

In [7]:
from sklearn.metrics import accuracy_score 

print ("Accuracy of 10NN (customized weights): %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Accuracy of 10NN (customized weights): 100.00 %


**Ưu điểm của KNN**
- Độ phức tạp tính toán của quá trình training là bằng 0.
- Việc dự đoán kết quả của dữ liệu mới rất đơn giản.
- Không cần giả sử gì về phân phối của các class.

**Nhược điểm của KNN**
- KNN rất nhạy cảm với nhiễu khi K nhỏ.
- Như đã nói, KNN là một thuật toán mà mọi tính toán đều nằm ở khâu test. Trong đó việc tính khoảng cách tới từng điểm dữ liệu trong training set sẽ tốn rất nhiều thời gian, đặc biệt là với các cơ sở dữ liệu có số chiều lớn và có nhiều điểm dữ liệu. Với K càng lớn thì độ phức tạp cũng sẽ tăng lên. Ngoài ra, việc lưu toàn bộ dữ liệu trong bộ nhớ cũng ảnh hưởng tới hiệu năng của KNN.